#!/bin/bash

# @brief    Скрипт для сборки OpenVPNToggler в Docker контейнере
# @param    IMAGE   Название образа, из которого будет собран Docker образ

#
# Константы
#

# @brief    Версия скрипта
readonly COMMON_VERSION="1.0.0"
# @brief    Название скрипта
readonly COMMON_SCRIPT_FILE="$(basename "$0")"
# @brief    Путь к скрипту
readonly COMMON_SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
# @brief    Путь к лог файлу
readonly COMMON_LOG_FILE="/tmp/$COMMON_SCRIPT_FILE.log"
# @brief    Путь к выходной директории
readonly COMMON_OUTPUT_DIR="$COMMON_SCRIPT_DIR/../output"
# @brief    Название Docker-образа
readonly COMMON_IMAGE_NAME="open-vpn-builder"

# @brief    Код успешного выполнения операции
readonly ALL_OK=0
# @brief    Код неуспешного выполнения операции
readonly NOT_OK=1

#
# Функции
#

# @brief    Основная функция
# @details  Данная функция выполняет вызов dpkg-buildpackage,
#               копирование выходных файлов в output и вызов debclean
# @brief    IMAGE Название образа, из которого будет собран Docker образ
# @return   Возвращает ALL_OK в случае успешного выполнения всех действий.
#               В противном случае, возвращает NOT_OK
function main ()
{
    local IMAGE="$1"

    if ! prepare
    then
        return $NOT_OK
    fi

    local DOCKER_ARGS=""

    DOCKER_ARGS+="--build-arg UID=$(id -u) "
    DOCKER_ARGS+="--build-arg GID=$(id -g) "
    if [ -n "$IMAGE" ]
    then
        DOCKER_ARGS+="--build-arg BASE_IMAGE=$IMAGE "
    fi

    echo -n "Сборка Docker-образа... "
    if ! docker build --tag "$COMMON_IMAGE_NAME" $DOCKER_ARGS -f "Dockerfile.auto" . >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Ошибка!"
        echo "Подробности:"
        echo "cat $COMMON_LOG_FILE"
        return $NOT_OK
    fi
    echo "Выполнено!"

    echo -n "Сборка пакета... "
    if ! docker run --rm -v "$COMMON_OUTPUT_DIR":/build/open-vpn-toggler/output "$COMMON_IMAGE_NAME" >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Ошибка!"
        echo "Подробности:"
        echo "cat $COMMON_LOG_FILE"
        return $NOT_OK
    fi
    echo "Выполнено!"

    local USER_NAME="$(getent passwd "${SUDO_USER:-$USER}" | cut -d: -f6 2>/dev/null || echo "$USER")"

    echo -n "Удаление Docker-образа... "
    if ! docker rmi "$COMMON_IMAGE_NAME" >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Ошибка!"
        echo "Подробности:"
        echo "cat $COMMON_LOG_FILE"
        return $NOT_OK        
    fi
    echo "Выполнено!"

    return $ALL_OK
}

# @brief    Функция подготовки к работе
# @details  Данная функция выполняет проверку наличия docker,
#               инициализацию COMMON_LOG_FILE и выходной директории
# @return   Возвращает ALL_OK в случае успешной подготовки к работе.
#               В противном случае, возвращет NOT_OK
function prepare ()
{
    echo -n "Подготовка рабочего окружения... "

    if ! command -v docker >> /dev/null 2>&1
    then
        echo "Не удалось обнаружить docker!"
        return $NOT_OK
    fi

    if ! truncate -s 0 "$COMMON_LOG_FILE" >> /dev/null 2>&1
    then
        echo "Не удалось создать лог файл $COMMON_LOG_FILE!"
        return $NOT_OK
    fi

    if ! [ -w "$COMMON_LOG_FILE" ]
    then
        echo "Лог файл $COMMON_LOG_FILE закрыт для записи!"
        return $NOT_OK
    fi

    if ! mkdir -p "$COMMON_OUTPUT_DIR" >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Не удалось создать выходную директорию!"
        echo "Подробности:"
        echo "cat $COMMON_LOG_FILE"
        return $NOT_OK
    fi

    docker rmi "$COMMON_IMAGE_NAME" >> "$COMMON_LOG_FILE" 2>&1

    echo "Выполнено!"

    return $ALL_OK
}

#
# Точка входа в скрипт
#

main "$@"
exit $?

