#!/bin/bash

# @brief    Скрипт для сборки OpenVPNToggler в текущей среде
# @param    IS_SHOW_LOG Флаг вывода содержимого лог-файла

#
# Константы
#

# @brief    Версия скрипта
readonly COMMON_VERSION="1.0.0"
# @brief    Название скрипта
readonly COMMON_SCRIPT_FILE="$(basename "$0")"
# @brief    Путь к скрипту
readonly COMMON_SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
# @brief    Путь к лог файлу
readonly COMMON_LOG_FILE="/tmp/$COMMON_SCRIPT_FILE.log"
# @brief    Путь к выходной директории
readonly COMMON_OUTPUT_DIR="$COMMON_SCRIPT_DIR/../output"
# @brief    Флаг вывода содержимого лог-файла
readonly COMMON_IS_SHOW_LOG="$1"

# @brief    Код успешного выполнения операции
readonly ALL_OK=0
# @brief    Код неуспешного выполнения операции
readonly NOT_OK=1

#
# Функции
#

# @brief    Основная функция
# @details  Данная функция выполняет вызов dpkg-buildpackage,
#               копирование выходных файлов в output и вызов debclean
# @return   Возвращает ALL_OK в случае успешного выполнения всех действий.
#               В противном случае, возвращает NOT_OK
function main ()
{
    if ! prepare
    then
        return $NOT_OK
    fi

    echo -n "Сборка пакета... "
    if ! dpkg-buildpackage -us -uc >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Ошибка!"
        showLog
        return $NOT_OK
    fi
    echo "Выполнено!"
    
    echo -n "Подготовка выходных файлов... "
    if ! mv ../open-vpn-toggler-* "$COMMON_OUTPUT_DIR" >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Ошибка!"
        showLog
        return $NOT_OK
    fi
    if ! mv ../open-vpn-toggler_* "$COMMON_OUTPUT_DIR" >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Ошибка!"
        showLog
        return $NOT_OK
    fi
    echo "Выполнено!"
    
    echo -n "Очистка... "
    debclean >> "$COMMON_LOG_FILE" 2>&1
    echo "Выполнено!"

    return $ALL_OK
}

# @brief    Функция подготовки к работе
# @details  Данная функция выполняет инициализацию COMMON_LOG_FILE и 
#               выходной директории
# @return   Возвращает ALL_OK в случае успешной подготовки к работе.
#               В противном случае, возвращет NOT_OK
function prepare ()
{
    echo -n "Подготовка рабочего окружения... "

    if ! truncate -s 0 "$COMMON_LOG_FILE" >> /dev/null 2>&1
    then
        echo "Не удалось создать лог файл $COMMON_LOG_FILE!"
        return $NOT_OK
    fi

    if ! [ -w "$COMMON_LOG_FILE" ]
    then
        echo "Лог файл $COMMON_LOG_FILE закрыт для записи!"
        return $NOT_OK
    fi

    if ! mkdir -p "$COMMON_OUTPUT_DIR" >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Не удалось создать выходную директорию!"
        showLog
        return $NOT_OK
    fi

    echo "Выполнено!"

    return $ALL_OK
}

# @brief    Функция вывода лога
# @details  Данная функция выводит содержимое COMMON_LOG_FILE, если COMMON_IS_SHOW_LOG равен 1.
#                противном случае выводит команду для показа содержимого COMMON_LOG_FILE
# @return   Возвращает ALL_OK
function showLog()
{
    if [ "$COMMON_IS_SHOW_LOG" == "1" ]
    then
        cat "$COMMON_LOG_FILE"
    else
        echo "Подробности:"
        echo "cat $COMMON_LOG_FILE"
    fi

    return $ALL_OK
}

#
# Точка входа в скрипт
#

main "$@"
exit $?

