#!/bin/bash

# @brief    Скрипт для подготовки к установке OpenVPNToggler

#
# Константы
#

# @brief    Версия скрипта
readonly COMMON_VERSION="1.0.1"
# @brief    Название скрипта
readonly COMMON_SCRIPT_FILE="$(basename "$0")"
# @brief    Путь к скрипту
readonly COMMON_SCRIPT_DIR="$(dirname "$(readlink -f "$0")")"
# @brief    Путь к лог файлу
readonly COMMON_LOG_FILE="/tmp/$COMMON_SCRIPT_FILE.log"
# @brief    Путь до директори OpenVPNToggler
readonly COMMON_DIR="/home/$SUDO_USER/.config/OpenVPNToggler/"
# @brief    Путь до конфигурационного файла VPN
readonly COMMON_CFG_FILE="/home/$SUDO_USER/.config/OpenVPNToggler/config.ovpn"

# @brief    Код успешного выполнения операции
readonly ALL_OK=0
# @brief    Код неуспешного выполнения операции
readonly NOT_OK=1

#
# Функции
#

# @brief    Основная функция
# @details  Данная функция выполняет удаление пакетов OpenVPN и удаление их репозиториев
# @return   Возвращает ALL_OK в случае успешного выполнения всех действий.
#               В противном случае, возвращает NOT_OK
function main ()
{
    if [ "$USER" != "root" ]
    then
        echo "Запустите скрипт при помощи sudo!"
        return $NOT_OK
    fi

    if ! truncate -s 0 "$COMMON_LOG_FILE" 2> /dev/null
    then
        echo "Не удалось создать $COMMON_LOG_FILE!"
        return $NOT_OK
    fi

    if sudo -u "$SUDO_USER" open-vpn-toggler "get" >> "$COMMON_LOG_FILE" 2>&1
    then
        echo -n "Отключение VPN..."
        sudo -u "$SUDO_USER" open-vpn-toggler >> "$COMMON_LOG_FILE" 2>&1
        echo "Выполнено!"
    fi

    local PACKAGES=(openvpn3
                    openvpn-systemd-resolved)
    local PACKAGE=""
   
    for PACKAGE in "${PACKAGES[@]}"
    do
        echo -n "Удаление пакета $PACKAGE... "
        if ! apt remove -y "$PACKAGE" >> "$COMMON_LOG_FILE" 2>&1
        then
            echo "Ошибка!"
            echo "Подробности:"
            echo "cat $COMMON_LOG_FILE"
            return $NOT_OK
        fi
        echo "Выполнено!"
    done

    echo -n "Удаление репозиториев OpenVPN... "
    rm -r /etc/apt/keyrings/openvpn.asc         >> "$COMMON_LOG_FILE" 2>&1
    rm -r /etc/apt/sources.list.d/openvpn3.list >> "$COMMON_LOG_FILE" 2>&1
    if ! apt update >> "$COMMON_LOG_FILE" 2>&1
    then
        echo "Ошибка!"
        echo "Подробности:"
        echo "cat $COMMON_LOG_FILE"
        return $NOT_OK
    fi
    echo "Выполнено!"
    
    echo -n "Удаление прочих зависимостей... "
    apt autoremove -y >> "$COMMON_LOG_FILE" 2>&1
    echo "Выполнено!"
    
    rm -r "$COMMON_LOG_FILE" 2> /dev/null

    return $ALL_OK
}

# @brief    Путь к сессии
COMMON_SESSION_PATH=""

# @brief    Функция получения пути сессии VPN
# @details  Данная функция выполняет поиск пути сессии с конфигурационным файлом COMMON_CFG_FILE.
#               Найденный путь записывается в COMMON_SESSION_PATH
# @return   Возвращает ALL_OK в случае успешного подключения к VPN.
#               В противном случае возвращет NOT_OK 
function getSessionPath ()
{
    local SESSION=""

    SESSION=$(openvpn3 sessions-list | awk -v cfg="$COMMON_CFG_FILE" '
    /^-----------------------------------------------------------------------------$/ { in_block = 1; path = "" }
    /^ *Path:/ && in_block { path = $2 }
    /^ *Config name:/ && in_block {
        if ($3 == cfg) {
            print path
            exit
        }
    }
    ')

    if [ -z "$SESSION" ]
    then
        return $NOT_OK
    fi

    COMMON_SESSION_PATH="$SESSION"
    return $ALL_OK
}

#
# Точка входа в скрипт
#

main "$@"
exit $?

